services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: unless-stopped
    depends_on:
      - "nginx-proxy"
    volumes_from:
       - "nginx-proxy"
    volumes:
       - ./certs:/etc/nginx/certs:rw
       - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
        - DEFAULT_EMAIL=CHANGE THIS
    networks:
      - proxy

  frontend:
    image: nginx:1.29-alpine-slim
    container_name: frontend
    restart: unless-stopped
    expose:
        - "80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy
    environment:
      - VIRTUAL_HOST=CHANGETHIS
      - LETSENCRYPT_HOST=CHANGETHIS

  backend:
    build: backend
    image: backend
    container_name: backend
    restart: unless-stopped
    volumes:
      - CHANGE THIS
      - ./db:/home/app/db:rw
      - ./uploads:/home/app/uploads:rw
    networks:
      - proxy
      
  # mongo:
  #   image: mongo
  #   container_name: mongo
  #   restart: always
  #   volumes:
  #     - ./data:/data

networks:
  proxy:
    driver: bridge
        
