- name: Prepare SSH key
  run: |
    echo "${{ secrets.VM_SSH_KEY }}" > key.pem
    chmod 600 key.pem

- name: Deploy to VM
  uses: appleboy/ssh-action@v1.2.0
  with:
    host: ${{ secrets.VM_HOST }}
    username: root
    key_path: key.pem
    script_stop: true
    debug: true
    script: |
      cd project-docflow/
      docker compose down
      git pull
      docker compose build
      docker compose up -d
